package com.medicalcenterapi.model.others;

public enum Speciality {
    ALLERGYANDIMMUNOLOGY,
    ANESTHESIOLOGY,
    DERMATOLOGY,
    RADIOLOGY,
    EMERGENCY,
    FAMILY,
    INTERNAL,
    GENETICS,
    NEUROLOGY,
    NUCLEAR,
    OBSTETRICS,
    GYNECOLOGY,
    OPHTHALMOLOGY,
    PATHOLOGY,
    PEDIATRICS,
    REHABILITATION,
    PSYCHIATRY,
    ONCOLOGY,
    SURGERY,
    UROLOGY,

    }
